gemini integration
Vikit-ai/sdk pull request #164
Opened 2024-11-17 13:52 UTC by leclem

quality controls

cutting video at the right time work

examples

script_example.py

Better quality function

changes working

work working

commit

solving bugs and code reviews

sonarcloud corrections

test_quality_check added

removing prints

removing url

generating zoom video in case regeneration fails

bug lower

new webp format

2024-11-17 13:52 UTC, leclem commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/164?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#164** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/164?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/164?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#163** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/163?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#162** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/162?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#161** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/161?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#160** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/160?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#159** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/159?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#158** <a href="https://app.graphite.dev/github/pr/Vikit-ai/sdk/158?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-17 23:04 UTC, jeffmac-aix requested changes

2024-11-17 23:04 UTC, jeffmac-aix commented on vikit/video/video.py
> +            elif is_qualitative_until != -1:
The logic is fairly hard to review/follow, as we have 3 and on the while loop, and here we unravel the different cases by infering the logic from the previous if  a and b block. Any ways to make this part easier to follow?

2024-11-17 23:04 UTC, jeffmac-aix commented on vikit/video/video.py
> +
I do not understand the hardcoded return values here, and why we assume is_composite is false, as composite inherits from video too, so this statement would be erroneous

2024-11-18 09:36 UTC, leclem commented on vikit/video/composite_video.py
> +            fps=24, #sum_files_fps / number_files,
Having videos with different FPS is the reason we had and have the glitch of freezing videos
In practice, all of our videos are always at 24 fps since two months because this is how we solved it. All of our divisions lead mathematically to 24 fps. So I can put it back or make it clear that the result of  sum_files_fps / number_files is always 24

2024-11-18 16:25 UTC, leclem commented on vikit/video/video.py
> +
The is_qualitative functions are old deprecated functions for the first version, indeed

For "is_composite"  we need a default functions so I can call it in build, and by default I set the value to false. I could have set None. In composite videos, I overide this function as you can see in "composite_video" of other PRs

2024-11-19 16:15 UTC, jeffmac-aix commented on vikit/video/composite_video.py
> +            fps=24, #sum_files_fps / number_files,
lgtm, we may just remove this as it is set by default on the ffmpeg wrapper

2024-11-19 16:19 UTC, jeffmac-aix approved these changes
lgtm

2024-11-19 16:20 UTC, merged